[project]
name = "compone-preline"
version = "0.1.0"
description = "Components for Preline UI (https://preline.co)"
license = "MIT"
authors = [{ name = "GyÃ¶rgy Kiss", email = "gyorgy@duck.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "compone>=0.4.0"
]
